import { businessTypes } from "../src/data/mockData.js";

const OPENROUTER_CHAT_COMPLETIONS_URL =
  "https://openrouter.ai/api/v1/chat/completions";
const DEFAULT_OPENROUTER_MODEL = "openai/gpt-4.1-mini";
const ANSWER_HUB_TIMEOUT_MS = 14000;

export async function generateAnswerHub(payload = {}, env = process.env) {
  const request = normalizeAnswerHubPayload(payload);
  const fallbackHub = buildFallbackAnswerHub(request, env);
  const openRouterApiKey = getOpenRouterApiKey(env);

  if (!openRouterApiKey) return fallbackHub;

  try {
    const response = await createOpenRouterChatCompletion(env, openRouterApiKey, {
      model: env.OPENROUTER_ANSWER_MODEL || env.OPENROUTER_MODEL || DEFAULT_OPENROUTER_MODEL,
      messages: [
        {
          role: "system",
          content:
            "You generate concise local-business FAQ content for answer engines. Return strict JSON only. Do not invent unverified guarantees, prices, discounts, or license claims.",
        },
        {
          role: "user",
          content: buildAnswerHubPrompt(request),
        },
      ],
      temperature: 0.25,
      response_format: { type: "json_object" },
    });
    const parsed = parseJsonResponse(response);
    const items = normalizeGeneratedItems(parsed.items, request);

    if (items.length < 4) {
      throw new Error("OpenRouter returned too few answer hub items.");
    }

    return finalizeAnswerHub(
      {
        ...fallbackHub,
        mode: "openrouter-answer-builder",
        title:
          parsed.title ||
          `${request.profile.name || "Local business"} direct-answer hub`,
        items,
        intentSummary: buildIntentSummary(items),
        providerStatus: [
          {
            provider: "OpenRouter",
            status: "live",
            detail: "Intent questions and direct answers were generated by the live model.",
          },
        ],
      },
      request,
      env
    );
  } catch (error) {
    return {
      ...fallbackHub,
      mode: "answer-builder-fallback",
      providerStatus: [
        {
          provider: "OpenRouter",
          status: "fallback",
          detail:
            error instanceof Error
              ? error.message
              : "Live answer generation failed.",
        },
      ],
    };
  }
}

export function prepareAnswerHubForSave(answerHub = {}, payload = {}, env = process.env) {
  const request = normalizeAnswerHubPayload(payload);
  const items = normalizeGeneratedItems(answerHub.items || [], request);

  return finalizeAnswerHub(
    {
      ...answerHub,
      mode: answerHub.mode || "dashboard-edited",
      title:
        answerHub.title ||
        `${request.profile.name || "Local business"} direct-answer hub`,
      status: answerHub.status || "ready",
      items,
      intentSummary: buildIntentSummary(items),
      providerStatus: answerHub.providerStatus || [],
    },
    request,
    env
  );
}

export function buildWidgetScript({ answerHub }) {
  const approvedItems = getApprovedItems(answerHub);
  const payload = {
    title: answerHub?.title || "Direct Answers",
    items: approvedItems.map((item) => ({
      question: item.question,
      answer: item.answer,
    })),
    schemaJson: buildFaqSchemaJson({
      title: answerHub?.title || "Direct Answers",
      profile: answerHub?.profileSnapshot || {},
      items: approvedItems,
    }),
  };

  return `(function(){var data=${JSON.stringify(payload)};var script=document.currentScript;function ready(fn){if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",fn,{once:true});}else{fn();}}function text(value){return document.createTextNode(value||"");}function render(){var targetId=script&&script.getAttribute("data-target");var mount=targetId?document.getElementById(targetId):null;if(!mount){mount=document.createElement("section");if(script&&script.parentNode){script.parentNode.insertBefore(mount,script);}else{document.body.appendChild(mount);}}mount.className=(mount.className?mount.className+" ":"")+"aeo-answer-hub";var style=document.createElement("style");style.textContent=".aeo-answer-hub{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;border:1px solid #d9e0e8;border-radius:8px;padding:18px;background:#fff;color:#17202a}.aeo-answer-hub h2{font-size:22px;margin:0 0 14px}.aeo-answer-hub details{border-top:1px solid #edf1f5;padding:12px 0}.aeo-answer-hub summary{cursor:pointer;font-weight:750}.aeo-answer-hub p{color:#475569;line-height:1.55;margin:8px 0 0}";document.head.appendChild(style);var heading=document.createElement("h2");heading.appendChild(text(data.title));mount.appendChild(heading);data.items.forEach(function(item){var row=document.createElement("details");var summary=document.createElement("summary");summary.appendChild(text(item.question));var answer=document.createElement("p");answer.appendChild(text(item.answer));row.appendChild(summary);row.appendChild(answer);mount.appendChild(row);});var schema=document.createElement("script");schema.type="application/ld+json";schema.text=JSON.stringify(data.schemaJson);document.head.appendChild(schema);}ready(render);})();`;
}

function buildFallbackAnswerHub(request, env) {
  const profile = request.profile;
  const items = buildBaseItems(request).map((item, index) =>
    buildItem(item, index)
  );

  return finalizeAnswerHub(
    {
      id: "",
      businessId: request.businessId || "",
      title: `${profile.name || "Local business"} direct-answer hub`,
      status: "ready",
      mode: "local-answer-builder",
      items,
      intentSummary: buildIntentSummary(items),
      providerStatus: [
        {
          provider: "Local answer builder",
          status: "ready",
          detail: "Questions and answers were generated from saved business facts.",
        },
      ],
    },
    request,
    env
  );
}

function buildBaseItems(request) {
  const profile = request.profile;
  const businessType = request.businessType;
  const services = splitCsv(profile.services);
  const primaryService =
    services[0] || businessType.highIntentService || businessType.categoryTerm;
  const secondService = services[1] || businessType.urgentNeed || primaryService;
  const city = extractCity(profile.market);
  const area = profile.serviceArea || profile.market || city;
  const contact = profile.phone || profile.bookingUrl || profile.website || "the business";
  const hours = profile.hours || "its published business hours";
  const credential = profile.credential
    ? ` The saved credential is ${profile.credential}.`
    : "";

  return [
    {
      intent: "Service Fit",
      question: `Does ${profile.name || "this business"} provide ${primaryService} in ${city}?`,
      answer: directAnswer(
        `Yes. ${profile.name || "The business"} lists ${primaryService} as a core service for ${area}. Customers can use ${contact} to confirm availability, timing, and booking details. The service page should cite the same business name, market, service area, and contact details so AI answers can verify the match.${credential}`
      ),
      source: "Business profile",
      targetPage: serviceTarget(primaryService),
    },
    {
      intent: "Urgent Need",
      question: `Can ${profile.name || "this business"} help with ${businessType.urgentNeed || secondService} near ${city}?`,
      answer: directAnswer(
        `Yes. ${profile.name || "The business"} lists ${businessType.urgentNeed || secondService} and related ${businessType.categoryTerm || "local service"} work for ${area}. The saved hours are ${hours}. Customers should use ${contact} for current dispatch, appointment, or availability details before visiting or booking.`
      ),
      source: "Audit prompts",
      targetPage: serviceTarget(businessType.urgentNeed || secondService),
    },
    {
      intent: "Service Area",
      question: `What areas does ${profile.name || "this business"} serve around ${city}?`,
      answer: directAnswer(
        `Fact: ${profile.name || "The business"} identifies ${area} as its local service area. Its website should repeat those same locations near service answers, contact details, and schema markup so AI systems connect the business to ${city} searches without relying on third-party directory guesses.`
      ),
      source: "Source-of-truth profile",
      targetPage: "Service area page",
    },
    {
      intent: "Hours",
      question: `Is ${profile.name || "this business"} available on weekends or after hours in ${city}?`,
      answer: directAnswer(
        `Fact: The saved business hours for ${profile.name || "this business"} are ${hours}. If weekend, after-hours, or emergency availability changes by service, the website should state those constraints directly on the relevant service page and mirror them in FAQPage schema.`
      ),
      source: "Business hours",
      targetPage: "Contact page",
    },
    {
      intent: "Comparison",
      question: `Why choose ${profile.name || "this business"} instead of another ${businessType.serviceNoun || "local business"} in ${city}?`,
      answer: directAnswer(
        `Fact: ${profile.name || "The business"} should be compared on verified facts: ${profile.category || businessType.categoryTerm}, service coverage in ${area}, saved hours of ${hours}, and direct contact through ${contact}. AI answers are more likely to cite the business when these facts are stated clearly on owned pages.`
      ),
      source: "Competitor gap",
      targetPage: "About page",
    },
    {
      intent: "Booking",
      question: `How do customers book ${secondService} with ${profile.name || "this business"}?`,
      answer: directAnswer(
        `Fact: Customers can contact ${profile.name || "the business"} through ${contact} for ${secondService} in ${city}. The website should place the same booking route beside the direct answer, service description, and structured data so AI engines can cite one consistent customer action.`
      ),
      source: "Booking signal",
      targetPage: serviceTarget(secondService),
    },
  ];
}

function finalizeAnswerHub(answerHub, request, env) {
  const profile = request.profile || {};
  const items = normalizeGeneratedItems(answerHub.items || [], request);
  const title =
    answerHub.title || `${profile.name || "Local business"} direct-answer hub`;
  const approvedItems = items.filter((item) => item.approved !== false);
  const schemaJson = buildFaqSchemaJson({ title, profile, items: approvedItems });
  const visualHtml = buildVisualHtml({ title, items: approvedItems });
  const appBaseUrl = getAppBaseUrl(env);
  const businessId = answerHub.businessId || request.businessId || "";
  const embedCode = `<script async src="${appBaseUrl}/api/entity-widget?businessId=${encodeURIComponent(
    businessId || "YOUR_BUSINESS_ID"
  )}"></script>`;

  return {
    id: answerHub.id || "",
    businessId,
    status: answerHub.status || "ready",
    title,
    mode: answerHub.mode || "local-answer-builder",
    items,
    visualHtml,
    schemaType: "FAQPage",
    schemaJson,
    embedCode,
    widgetPayload: {
      title,
      approvedCount: approvedItems.length,
      questions: approvedItems.map((item) => item.question),
    },
    intentSummary: answerHub.intentSummary || buildIntentSummary(items),
    providerStatus: answerHub.providerStatus || [],
    profileSnapshot: profile,
    generatedAt: answerHub.generatedAt || new Date().toISOString(),
  };
}

function buildAnswerHubPrompt(request) {
  const profile = request.profile;
  const businessType = request.businessType;
  const auditQuestions = (request.auditReport?.prompts || [])
    .map((prompt) => prompt.query || prompt.prompt)
    .filter(Boolean)
    .slice(0, 8);
  const entityGaps = (request.auditReport?.entityGaps || [])
    .map((gap) => `${gap.title}: ${gap.detail}`)
    .slice(0, 6);

  return [
    "Create an AI-optimized direct-answer Q&A hub for a local business.",
    "Return JSON with this exact shape: {\"title\":\"...\",\"items\":[{\"intent\":\"...\",\"question\":\"...\",\"answer\":\"...\",\"source\":\"...\",\"targetPage\":\"...\",\"approved\":true}]}",
    "Rules:",
    "- Create 6 items.",
    "- Each answer must be 40-80 words.",
    "- Start each answer with Yes, No, or Fact.",
    "- Include geography when available.",
    "- Use only verified facts from the profile. If a price, warranty, emergency guarantee, or same-day claim is not provided, say customers should confirm it.",
    "- Do not mention this SaaS, schema, LLMs, or AI optimization in the customer-facing answer text.",
    "",
    `Business: ${profile.name || "Unknown"}`,
    `Business type: ${businessType.label || profile.businessType || "Local Business"}`,
    `Category: ${profile.category || businessType.categoryTerm || "Unknown"}`,
    `Website: ${profile.website || "Unknown"}`,
    `Market: ${profile.market || "Unknown"}`,
    `Address: ${profile.address || "Unknown"}`,
    `Phone: ${profile.phone || "Unknown"}`,
    `Hours: ${profile.hours || "Unknown"}`,
    `Service area: ${profile.serviceArea || "Unknown"}`,
    `Services: ${profile.services || businessType.highIntentService || "Unknown"}`,
    `Credential: ${profile.credential || "Unknown"}`,
    `Booking URL: ${profile.bookingUrl || "Unknown"}`,
    `Competitors: ${request.competitors.join(", ") || "Unknown"}`,
    auditQuestions.length ? `Existing audit prompts: ${auditQuestions.join(" | ")}` : "",
    entityGaps.length ? `Entity gaps: ${entityGaps.join(" | ")}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

async function createOpenRouterChatCompletion(env, apiKey, request) {
  const timeoutMs = parseIntegerEnv(
    env.ANSWER_HUB_TIMEOUT_MS,
    ANSWER_HUB_TIMEOUT_MS,
    5000,
    60000
  );
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetch(OPENROUTER_CHAT_COMPLETIONS_URL, {
      method: "POST",
      headers: buildOpenRouterHeaders(env, apiKey),
      body: JSON.stringify(request),
      signal: controller.signal,
    });

    if (!response.ok) {
      const detail = await response.text();
      throw new Error(`OpenRouter HTTP ${response.status}: ${truncateText(detail, 400)}`);
    }

    return response.json();
  } catch (error) {
    if (error?.name === "AbortError") {
      throw new Error(
        `OpenRouter answer hub timed out after ${Math.round(timeoutMs / 1000)} seconds.`
      );
    }
    throw error;
  } finally {
    clearTimeout(timeout);
  }
}

function parseJsonResponse(response) {
  const content = response?.choices?.[0]?.message?.content;
  const text = Array.isArray(content)
    ? content.map((item) => item.text || item.content || "").join("\n")
    : String(content || "");
  const cleaned = text
    .trim()
    .replace(/^```json\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/\s*```$/i, "");
  return JSON.parse(cleaned);
}

function normalizeAnswerHubPayload(payload) {
  const fallbackType =
    businessTypes.find((type) => type.id === payload.selectedBusinessType) ||
    businessTypes.find((type) => type.id === payload.businessType?.id) ||
    businessTypes[0];
  const businessType =
    payload.businessType && typeof payload.businessType === "object"
      ? { ...fallbackType, ...payload.businessType }
      : fallbackType;

  return {
    profile: payload.profile || {},
    businessId: payload.businessId || "",
    businessType,
    competitors: Array.isArray(payload.competitors) ? payload.competitors : [],
    monitoredLocations: Array.isArray(payload.monitoredLocations)
      ? payload.monitoredLocations
      : [],
    auditReport:
      payload.auditReport && typeof payload.auditReport === "object"
        ? payload.auditReport
        : null,
  };
}

function normalizeGeneratedItems(items, request) {
  const fallbackItems = buildBaseItems(request).map((item, index) =>
    buildItem(item, index)
  );
  const sourceItems = Array.isArray(items) && items.length > 0 ? items : fallbackItems;

  return sourceItems
    .map((item, index) =>
      buildItem(
        {
          intent: item.intent || fallbackItems[index]?.intent || "Direct Answer",
          question: item.question || fallbackItems[index]?.question || "",
          answer: item.answer || fallbackItems[index]?.answer || "",
          source: item.source || item.sourceReason || fallbackItems[index]?.source || "Business profile",
          targetPage: item.targetPage || fallbackItems[index]?.targetPage || "Service page",
          approved: item.approved !== false,
        },
        index
      )
    )
    .filter((item) => item.question && item.answer)
    .slice(0, 8);
}

function buildItem(item, index) {
  const answer = directAnswer(item.answer);
  return {
    id: item.id || `qa-${index + 1}-${slugify(item.question).slice(0, 36)}`,
    intent: String(item.intent || "Direct Answer").trim(),
    question: cleanSentence(item.question),
    answer,
    approved: item.approved !== false,
    source: String(item.source || "Business profile").trim(),
    targetPage: String(item.targetPage || "Service page").trim(),
    wordCount: countWords(answer),
  };
}

function buildIntentSummary(items) {
  return items.map((item) => ({
    intent: item.intent,
    question: item.question,
    source: item.source,
    approved: item.approved !== false,
  }));
}

function buildFaqSchemaJson({ title, profile, items }) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    name: title,
    about: profile?.name,
    mainEntity: items.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.answer,
      },
    })),
  };
}

function buildVisualHtml({ title, items }) {
  const rows = items
    .map(
      (item) =>
        `  <details class="aeo-answer-hub__item">\n    <summary>${escapeHtml(
          item.question
        )}</summary>\n    <p>${escapeHtml(item.answer)}</p>\n  </details>`
    )
    .join("\n");

  return `<section class="aeo-answer-hub" aria-label="${escapeHtml(
    title
  )}">\n  <h2>${escapeHtml(title)}</h2>\n${rows}\n</section>`;
}

function getApprovedItems(answerHub) {
  return (answerHub?.items || []).filter((item) => item.approved !== false);
}

function directAnswer(value) {
  const text = cleanSentence(value);
  if (/^(yes|no|fact)[:.]/i.test(text)) return text;
  return `Fact: ${text}`;
}

function cleanSentence(value) {
  return String(value || "")
    .replace(/\s+/g, " ")
    .trim();
}

function splitCsv(value) {
  return String(value || "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

function serviceTarget(service) {
  const label = String(service || "").trim();
  return label ? `${label} service page` : "Service page";
}

function extractCity(market) {
  return String(market || "the local market").split(",")[0].trim();
}

function countWords(value) {
  return String(value || "")
    .split(/\s+/)
    .filter(Boolean).length;
}

function slugify(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function escapeHtml(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function getAppBaseUrl(env) {
  if (env.APP_BASE_URL) return env.APP_BASE_URL.replace(/\/+$/, "");
  if (env.VERCEL_PROJECT_PRODUCTION_URL) {
    return `https://${env.VERCEL_PROJECT_PRODUCTION_URL}`.replace(/\/+$/, "");
  }
  if (env.VERCEL_URL) return `https://${env.VERCEL_URL}`.replace(/\/+$/, "");
  return "https://aeo-local-monitor.vercel.app";
}

function buildOpenRouterHeaders(env, apiKey) {
  const headers = {
    authorization: `Bearer ${apiKey}`,
    "content-type": "application/json",
    "x-title": "AEO Local Monitor",
  };
  const referer = getOpenRouterReferer(env);
  if (referer) headers["http-referer"] = referer;
  return headers;
}

function getOpenRouterReferer(env) {
  if (env.OPENROUTER_SITE_URL) return env.OPENROUTER_SITE_URL;
  if (env.VERCEL_PROJECT_PRODUCTION_URL) {
    return `https://${env.VERCEL_PROJECT_PRODUCTION_URL}`;
  }
  if (env.VERCEL_URL) return `https://${env.VERCEL_URL}`;
  return "";
}

function getOpenRouterApiKey(env) {
  return env.OPENROUTER_API_KEY || env.OPENROUTER_api_KEY || "";
}

function parseIntegerEnv(value, fallback, min, max) {
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(max, Math.max(min, parsed));
}

function truncateText(value, maxLength) {
  const text = String(value || "").replace(/\s+/g, " ").trim();
  return text.length > maxLength ? `${text.slice(0, maxLength)}...` : text;
}
